Repository ecmwf/anemoi-training, pull requests merged in 2024-12, with the labels that each got.

#178 fix weight mask calculation when using the remapper and no imputer
  CHANGELOG.md
  src/anemoi/training/train/forecaster.py
Labels: bug, No approval needed

#166 Feature/transfer-learning
  CHANGELOG.md
  src/anemoi/training/config/training/default.yaml
  src/anemoi/training/data/datamodule.py
  src/anemoi/training/data/dataset.py
  src/anemoi/training/train/forecaster.py
  src/anemoi/training/train/train.py
  src/anemoi/training/utils/checkpoint.py
Labels: contributor

#181 fix: allow None as graph save_path setting.
  src/anemoi/training/train/train.py
Labels: no changelog

#194 Fix for checkpoint loading.
  src/anemoi/training/train/train.py
Labels: bug, no changelog

#197 161 documentation for anemoi training broken
  README.md
  docs/conf.py
Labels: no changelog

#201 Remove excess metadata from variables
  src/anemoi/training/diagnostics/mlflow/logger.py
Labels: no changelog

#209 fix: set anemoi-models=0.4.1 as the minimum required version
  pyproject.toml
Labels: no changelog
