Repository ecmwf/anemoi-training, pull requests merged in 2024-11, with the labels that each got.

#119 fix: enable learningrate monitor automatically
  CHANGELOG.md
  src/anemoi/training/diagnostics/callbacks/__init__.py
Labels: bug

#38 Mlflow benchmark profiler update
  CHANGELOG.md
  docs/images/profiler/anemoi_profiler_architecture.png
  docs/images/profiler/anemoi_profiler_benchmark_profiler.png
  docs/images/profiler/anemoi_profiler_config.png
  docs/images/profiler/anemoi_profiler_high_level.png
  docs/images/profiler/anemoi_profiler_mlflow_integration.png
  docs/images/profiler/anemoi_profiler_mlflow_integration_2.png
  docs/images/profiler/anemoi_profiler_mlflow_integration_3.png
  docs/images/profiler/anemoi_profiler_speed_report.png
  docs/images/profiler/anemoi_profiler_speedreport_diagram.png
  docs/images/profiler/anemoi_profiler_training_rates.png
  docs/images/profiler/anemoi_profiler_validation_rates.png
  docs/images/profiler/example_memory_report.png
  docs/images/profiler/example_memory_timeline.png
  docs/images/profiler/example_model_summary.png
  docs/images/profiler/example_model_summary_2.png
  docs/images/profiler/example_system_report.png
  docs/images/profiler/example_time_report.png
  docs/images/profiler/idle_time_breakdown.png
  docs/images/profiler/kernel_breakdown_dfs.png
  docs/images/profiler/kernel_breakdown_plots.png
  docs/images/profiler/memory_snapshot_diagram.png
  docs/images/profiler/memory_snapshot_output.png
  docs/images/profiler/temporal_breakdown.png
  docs/index.rst
  docs/overview.rst
  docs/user-guide/benchmarking.rst
  pyproject.toml
  src/anemoi/training/commands/profiler.py
  src/anemoi/training/commands/train.py
  src/anemoi/training/config/diagnostics/benchmark_profiler/detailed.yaml
  src/anemoi/training/config/diagnostics/benchmark_profiler/simple.yaml
  src/anemoi/training/config/diagnostics/evaluation.yaml
  src/anemoi/training/config/training/default.yaml
  src/anemoi/training/diagnostics/callbacks/profiler.py
  src/anemoi/training/diagnostics/profilers.py
  src/anemoi/training/train/profiler.py
  src/anemoi/training/train/train.py
Labels: enhancement

#121 missing copyrigths
  docs/conf.py
  pyproject.toml
  src/anemoi/training/__init__.py
  src/anemoi/training/__main__.py
  src/anemoi/training/commands/__init__.py
  src/anemoi/training/config/__init__.py
  src/anemoi/training/data/__init__.py
  src/anemoi/training/diagnostics/__init__.py
  src/anemoi/training/diagnostics/mlflow/__init__.py
  src/anemoi/training/distributed/__init__.py
  src/anemoi/training/losses/__init__.py
  src/anemoi/training/train/__init__.py
  src/anemoi/training/utils/__init__.py
  src/hydra_plugins/anemoi_searchpath/__init__.py
  tests/diagnostics/test_callbacks.py
  tests/train/test_scaler.py
Labels: no changelog

#125 Fix missing checkpoint callbacks
  src/anemoi/training/diagnostics/callbacks/__init__.py
Labels: bug, no changelog

#94 Change how mlflow measures CPU memory usage
  CHANGELOG.md
  src/anemoi/training/diagnostics/mlflow/logger.py
Labels: contributor

#133 Graph config for stretched grid graph
  CHANGELOG.md
  src/anemoi/training/config/graph/stretched_grid.yaml
Labels: contributor

#135 Feature/update graph callbacks
  CHANGELOG.md
  src/anemoi/training/config/diagnostics/plot/detailed.yaml
  src/anemoi/training/config/diagnostics/plot/rollout_eval.yaml
  src/anemoi/training/diagnostics/callbacks/plot.py
  src/anemoi/training/diagnostics/plots.py
Labels: bug

#65 Rollout video of variable dynamics
  CHANGELOG.md
  src/anemoi/training/config/diagnostics/plot/rollout_eval.yaml
  src/anemoi/training/diagnostics/callbacks/plot.py
  src/anemoi/training/diagnostics/plots.py
Labels: enhancement

#146 dont check for tracking uri when running mlflow offline
  src/anemoi/training/diagnostics/logger.py
Labels: no changelog

#72 Feature/mask NaNs in training loss function
  CHANGELOG.md
  src/anemoi/training/config/training/default.yaml
  src/anemoi/training/train/forecaster.py
Labels: enhancement

#76 Feature/improve dataloader memory
  CHANGELOG.md
  docs/user-guide/distributed.rst
  src/anemoi/training/config/dataloader/native_grid.yaml
  src/anemoi/training/data/datamodule.py
  src/anemoi/training/data/dataset.py
  src/anemoi/training/diagnostics/callbacks/evaluation.py
  src/anemoi/training/diagnostics/callbacks/plot.py
  src/anemoi/training/distributed/strategy.py
  src/anemoi/training/train/forecaster.py
  src/anemoi/training/train/train.py
Labels: enhancement, aifs_v0.3_reproducibility

#154 Validation and Training dataset dates assertion
  src/anemoi/training/data/datamodule.py
Labels: no changelog, aifs_v0.3_reproducibility

#155 warmup config for reproducibility of aifs v0.3
  CHANGELOG.md
  docs/user-guide/training.rst
  src/anemoi/training/config/training/default.yaml
  src/anemoi/training/train/forecaster.py
Labels: aifs_v0.3_reproducibility

#169 Update logger.py
  src/anemoi/training/diagnostics/mlflow/logger.py
Labels: no changelog

#153 full shuffle of the dataset
  CHANGELOG.md
  src/anemoi/training/data/dataset.py
Labels: enhancement
