Repository ecmwf/anemoi-training, pull requests merged in 2024-09, with the labels that each got.

#37 fix: saving frequency bug for inference checkpoints
  CHANGELOG.md
  src/anemoi/training/diagnostics/callbacks/__init__.py
Labels: bug

#48 40 support dataset with missing timesteps
  CHANGELOG.md
  src/anemoi/training/data/dataset.py
  src/anemoi/training/utils/usable_indices.py
  tests/utils/test_usable_indices.py
Labels: enhancement

#26 23 plot a validation sample after long rollout
  CHANGELOG.md
  src/anemoi/training/config/diagnostics/eval_rollout.yaml
  src/anemoi/training/data/datamodule.py
  src/anemoi/training/diagnostics/callbacks/__init__.py
Labels: ATS approved

#61 [fix] Capture Anemoi Training subcommands in MLFlow
  CHANGELOG.md
  src/anemoi/training/commands/train.py
Labels: bug
