Repository ecmwf/anemoi-training, pull requests merged in 2024-10, with the labels that each got.

#66 fix version pinning
  pyproject.toml
Labels: contributor

#62 Fix mlflow command on python 3.9
  CHANGELOG.md
  src/anemoi/training/diagnostics/mlflow/auth.py
Labels: bug, ATS approved

#64 Make pin_memory of the Dataloader configurable
  CHANGELOG.md
  src/anemoi/training/config/dataloader/native_grid.yaml
  src/anemoi/training/data/datamodule.py
Labels: contributor

#79 Add output mask
  CHANGELOG.md
  src/anemoi/training/diagnostics/callbacks/__init__.py
  src/anemoi/training/train/forecaster.py
  src/anemoi/training/utils/masks.py
Labels: enhancement

#113 Fix changelog
  CHANGELOG.md
Labels: No approval needed
